### ISSUE TITLE
beam-postgres-0.5.4.2 failed to build with ghc 9.6.6

### ISSUE THREAD

**Issue by xiaoshihou514** [haskell-beam/beam#763]
`ghc --version`:
```
The Glorious Glasgow Haskell Compilation System, version 9.6.6
```

build output:
```
Resolving dependencies...
Build profile: -w ghc-9.6.6 -O1
In order, the following will be built (use -v for more details):
 - beam-postgres-0.5.4.2 (lib) (requires build)
 - deepsleep-0.1.0.0 (exe:deepsleep) (first run)
Starting     beam-postgres-0.5.4.2 (lib)
Building     beam-postgres-0.5.4.2 (lib)

Failed to build beam-postgres-0.5.4.2.
Build log (
/home/xiaoshihou/.cache/cabal/logs/ghc-9.6.6/beam-postgres-0.5.4.2-3b4da6ecb8dc9be49778740aa94fac281b4ac1374bd98637cb2c266906a29e85.log
):
Configuring library for beam-postgres-0.5.4.2..
Preprocessing library for beam-postgres-0.5.4.2..
Building library for beam-postgres-0.5.4.2..
[ 1 of 14] Compiling Database.Beam.Postgres.Syntax ( Database/Beam/Postgres/Syntax.hs, dist/build/Database/Beam/Postgres/Syntax.o, dist/build/Database/Beam/Postgres/Syntax.dyn_o )
[ 2 of 14] Compiling Database.Beam.Postgres.Types ( Database/Beam/Postgres/Types.hs, dist/build/Database/Beam/Postgres/Types.o, dist/build/Database/Beam/Postgres/Types.dyn_o )
[ 3 of 14] Compiling Database.Beam.Postgres.PgSpecific ( Database/Beam/Postgres/PgSpecific.hs, dist/build/Database/Beam/Postgres/PgSpecific.o, dist/build/Database/Beam/Postgres/PgSpecific.dyn_o )
[ 4 of 14] Compiling Database.Beam.Postgres.Full ( Database/Beam/Postgres/Full.hs, dist/build/Database/Beam/Postgres/Full.o, dist/build/Database/Beam/Postgres/Full.dyn_o )
[ 5 of 14] Compiling Database.Beam.Postgres.Extensions ( Database/Beam/Postgres/Extensions.hs, dist/build/Database/Beam/Postgres/Extensions.o, dist/build/Database/Beam/Postgres/Extensions.dyn_o )
[ 6 of 14] Compiling Database.Beam.Postgres.CustomTypes ( Database/Beam/Postgres/CustomTypes.hs, dist/build/Database/Beam/Postgres/CustomTypes.o, dist/build/Database/Beam/Postgres/CustomTypes.dyn_o )
[ 7 of 14] Compiling Database.Beam.Postgres.Connection ( Database/Beam/Postgres/Connection.hs, dist/build/Database/Beam/Postgres/Connection.o, dist/build/Database/Beam/Postgres/Connection.dyn_o )

Database/Beam/Postgres/Connection.hs:158:68: warning: [GHC-63397] [-Wname-shadowing]
    This binding for ‘field’ shadows the existing binding
      bound at Database/Beam/Postgres/Connection.hs:145:64
    |
158 |                                                 , Pg.errSQLField = field } ->
    |                                                                    ^^^^^

Database/Beam/Postgres/Connection.hs:163:64: warning: [GHC-63397] [-Wname-shadowing]
    This binding for ‘field’ shadows the existing binding
      bound at Database/Beam/Postgres/Connection.hs:145:64
    |
163 |                                             , Pg.errSQLField = field } ->
    |                                                                ^^^^^
[ 8 of 14] Compiling Database.Beam.Postgres.Migrate ( Database/Beam/Postgres/Migrate.hs, dist/build/Database/Beam/Postgres/Migrate.o, dist/build/Database/Beam/Postgres/Migrate.dyn_o )

Database/Beam/Postgres/Migrate.hs:86:20: error: [GHC-83865]
    • Couldn't match expected type: Tool.BeamMigrationBackend
                                      Postgres Pg
                  with actual type: (forall a. Pg a -> Pg a)
                                    -> (String -> IO (Tool.BeamMigrateConnection Postgres Pg))
                                    -> Tool.BeamMigrationBackend Postgres Pg
    • Probable cause: ‘Tool.BeamMigrationBackend’ is applied to too few arguments
      In the expression:
        Tool.BeamMigrationBackend
          "postgres"
          (unlines
             ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
              "",
              "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
              "", ....])
          (liftIOWithHandle getDbConstraints)
          (Db.sql92Deserializers
             <>
               Db.sql99DataTypeDeserializers
                 <>
                   Db.sql2008BigIntDataTypeDeserializers
                     <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
          (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
          "postgres.sql" pgPredConverter
          (mconcat
             [defaultActionProvider, defaultSchemaActionProvider,
              pgExtensionActionProvider, pgCustomEnumActionProvider])
          (\ options action
             -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                  $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
      In an equation for ‘migrationBackend’:
          migrationBackend
            = Tool.BeamMigrationBackend
                "postgres"
                (unlines
                   ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
                    "",
                    "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
                    ....])
                (liftIOWithHandle getDbConstraints)
                (Db.sql92Deserializers
                   <>
                     Db.sql99DataTypeDeserializers
                       <>
                         Db.sql2008BigIntDataTypeDeserializers
                           <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
                (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
                "postgres.sql" pgPredConverter
                (mconcat
                   [defaultActionProvider, defaultSchemaActionProvider,
                    pgExtensionActionProvider, ....])
                (\ options action
                   -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                        $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
   |
86 | migrationBackend = Tool.BeamMigrationBackend
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^...

Database/Beam/Postgres/Migrate.hs:108:26: error: [GHC-83865]
    • Couldn't match expected type: Pg ()
                  with actual type: Pg a0 -> IO (Either String a0)
    • The lambda expression ‘\ options action
                               -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                                    $ ...’
      has two value arguments,
        but its type ‘T.Text -> Pg ()’ has only one
      In the 9th argument of ‘Tool.BeamMigrationBackend’, namely
        ‘(\ options action
            -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                 $ \ conn
                     -> left show <$> withPgDebug (\ _ -> pure ()) conn action)’
      In the expression:
        Tool.BeamMigrationBackend
          "postgres"
          (unlines
             ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
              "",
              "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
              "", ....])
          (liftIOWithHandle getDbConstraints)
          (Db.sql92Deserializers
             <>
               Db.sql99DataTypeDeserializers
                 <>
                   Db.sql2008BigIntDataTypeDeserializers
                     <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
          (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
          "postgres.sql" pgPredConverter
          (mconcat
             [defaultActionProvider, defaultSchemaActionProvider,
              pgExtensionActionProvider, pgCustomEnumActionProvider])
          (\ options action
             -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                  $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
    |
108 |                         (\options action ->
    |                          ^^^^^^^^^^^^^^^^^^...

Database/Beam/Postgres/Migrate.hs:109:71: error: [GHC-83865]
    • Couldn't match type ‘T.Text’ with ‘[Char]’
      Expected: String
        Actual: T.Text
    • In the first argument of ‘fromString’, namely ‘options’
      In the first argument of ‘Pg.connectPostgreSQL’, namely
        ‘(fromString options)’
      In the first argument of ‘bracket’, namely
        ‘(Pg.connectPostgreSQL (fromString options))’
    |
109 |                             bracket (Pg.connectPostgreSQL (fromString options)) Pg.close $ \conn ->
    |                                                                       ^^^^^^^
[ 9 of 14] Compiling Database.Beam.Postgres.Debug ( Database/Beam/Postgres/Debug.hs, dist/build/Database/Beam/Postgres/Debug.o, dist/build/Database/Beam/Postgres/Debug.dyn_o )
[10 of 14] Compiling Database.Beam.Postgres.Conduit ( Database/Beam/Postgres/Conduit.hs, dist/build/Database/Beam/Postgres/Conduit.o, dist/build/Database/Beam/Postgres/Conduit.dyn_o )
Error: cabal: Failed to build beam-postgres-0.5.4.2 (which is required by
exe:deepsleep from deepsleep-0.1.0.0). See the build log above for details.
```

cabal file:
```cabal
    default-language: GHC2021
    -- no language extensions
```

**Comment by LaurentRDC** [comment]
Hmm this is strange. We use [GHC 9.6.4](https://github.com/haskell-beam/beam/blob/a60fe9baf0d8c7576c050ef029236ddb2f44bcc6/.github/workflows/build.yaml#L24C11-L24C33) for continuous testing, and I doubt that GHC 9.6.6 is *that* different. Let me try on my machine

**Comment by LaurentRDC** [comment]
I was able to compile `beam-postgres` using GHC 9.6.6 without any issues.

I notice that one of your build warnings says:

```
Database/Beam/Postgres/Connection.hs:158:68: warning: [GHC-63397] [-Wname-shadowing]
    This binding for ‘field’ shadows the existing binding
      bound at Database/Beam/Postgres/Connection.hs:145:64
    |
158 |                                                 , Pg.errSQLField = field } ->
    |                                                                    ^^^^^
```

However, line 158 of that file is different[ from the source of `beam-postgres-0.5.4.2`](https://github.com/haskell-beam/beam/blob/a60fe9baf0d8c7576c050ef029236ddb2f44bcc6/beam-postgres/Database/Beam/Postgres/Connection.hs#L158). That particular warning was fixed in commit 5c343025c117a3ffac0a0fd649a4d16e0e800539, many months before the 0.5.4.2 release.

Something is wrong with the source code you have, but I don't understand how you could have gotten that

**Comment by xiaoshihou514** [comment]
I would also try to remove cabal caches and try again in a sec...

**Comment by xiaoshihou514** [comment]
Actually, I see the same source code (as on my machine) on hackage.

![Screenshot_2025-05-27-19-01-55-719_org.mozilla.fennec_fdroid-edit.jpg](https://github.com/user-attachments/assets/03fa0ba8-e61f-4362-8a4c-c0c33e527f40)

![Screenshot_2025-05-27-19-02-14-612_org.mozilla.fennec_fdroid-edit.jpg](https://github.com/user-attachments/assets/64834f0c-5c3e-4075-9aa2-8c13c507ac5d)

Has there been a mistake in release?

**Comment by mlee-sg** [comment]
I have the same build failure using ghc-9.6.7 and up:

[ 7 of 14] Compiling Database.Beam.Postgres.Connection ( Database/Beam/Postgres/Connection.hs, dist/build/Database/Beam/Postgres/Connection.o, dist/build/Database/Beam/Postgres/Connection.dyn_o )

Database/Beam/Postgres/Connection.hs:158:68: warning: [GHC-63397] [-Wname-shadowing]
    This binding for ‘field’ shadows the existing binding
      bound at Database/Beam/Postgres/Connection.hs:145:64
    |
158 |                                                 , Pg.errSQLField = field } ->
    |                                                                    ^^^^^

Database/Beam/Postgres/Connection.hs:163:64: warning: [GHC-63397] [-Wname-shadowing]
    This binding for ‘field’ shadows the existing binding
      bound at Database/Beam/Postgres/Connection.hs:145:64
    |
163 |                                             , Pg.errSQLField = field } ->
    |                                                                ^^^^^
[ 8 of 14] Compiling Database.Beam.Postgres.Migrate ( Database/Beam/Postgres/Migrate.hs, dist/build/Database/Beam/Postgres/Migrate.o, dist/build/Database/Beam/Postgres/Migrate.dyn_o )

Database/Beam/Postgres/Migrate.hs:86:20: error: [GHC-83865]
    • Couldn't match expected type: Tool.BeamMigrationBackend
                                      Postgres Pg
                  with actual type: (forall a. Pg a -> Pg a)
                                    -> (String -> IO (Tool.BeamMigrateConnection Postgres Pg))
                                    -> Tool.BeamMigrationBackend Postgres Pg
    • Probable cause: ‘Tool.BeamMigrationBackend’ is applied to too few arguments
      In the expression:
        Tool.BeamMigrationBackend
          "postgres"
          (unlines
             ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
              "",
              "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
              "", ....])
          (liftIOWithHandle getDbConstraints)
          (Db.sql92Deserializers
             <>
               Db.sql99DataTypeDeserializers
                 <>
                   Db.sql2008BigIntDataTypeDeserializers
                     <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
          (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
          "postgres.sql" pgPredConverter
          (mconcat
             [defaultActionProvider, defaultSchemaActionProvider,
              pgExtensionActionProvider, pgCustomEnumActionProvider])
          (\ options action
             -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                  $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
      In an equation for ‘migrationBackend’:
          migrationBackend
            = Tool.BeamMigrationBackend
                "postgres"
                (unlines
                   ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
                    "",
                    "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
                    ....])
                (liftIOWithHandle getDbConstraints)
                (Db.sql92Deserializers
                   <>
                     Db.sql99DataTypeDeserializers
                       <>
                         Db.sql2008BigIntDataTypeDeserializers
                           <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
                (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
                "postgres.sql" pgPredConverter
                (mconcat
                   [defaultActionProvider, defaultSchemaActionProvider,
                    pgExtensionActionProvider, ....])
                (\ options action
                   -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                        $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
   |
86 | migrationBackend = Tool.BeamMigrationBackend
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^...

Database/Beam/Postgres/Migrate.hs:108:26: error: [GHC-83865]
    • Couldn't match expected type: Pg ()
                  with actual type: Pg a0 -> IO (Either String a0)
    • The lambda expression ‘\ options action
                               -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                                    $ ...’
      has two value arguments,
        but its type ‘T.Text -> Pg ()’ has only one
      In the 9th argument of ‘Tool.BeamMigrationBackend’, namely
        ‘(\ options action
            -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                 $ \ conn
                     -> left show <$> withPgDebug (\ _ -> pure ()) conn action)’
      In the expression:
        Tool.BeamMigrationBackend
          "postgres"
          (unlines
             ["For beam-postgres, this is a libpq connection string which can either be a list of key value pairs or a URI",
              "",
              "For example, 'host=localhost port=5432 dbname=mydb connect_timeout=10' or 'dbname=mydb'",
              "", ....])
          (liftIOWithHandle getDbConstraints)
          (Db.sql92Deserializers
             <>
               Db.sql99DataTypeDeserializers
                 <>
                   Db.sql2008BigIntDataTypeDeserializers
                     <> postgresDataTypeDeserializers <> Db.beamCheckDeserializers)
          (BCL.unpack . (<> ";") . pgRenderSyntaxScript . fromPgCommand)
          "postgres.sql" pgPredConverter
          (mconcat
             [defaultActionProvider, defaultSchemaActionProvider,
              pgExtensionActionProvider, pgCustomEnumActionProvider])
          (\ options action
             -> bracket (Pg.connectPostgreSQL (fromString options)) Pg.close
                  $ \ conn -> left show <$> withPgDebug (\ _ -> pure ()) conn action)
    |
108 |                         (\options action ->
    |                          ^^^^^^^^^^^^^^^^^^...

Database/Beam/Postgres/Migrate.hs:109:71: error: [GHC-83865]
    • Couldn't match type ‘T.Text’ with ‘[Char]’
      Expected: String
        Actual: T.Text
    • In the first argument of ‘fromString’, namely ‘options’
      In the first argument of ‘Pg.connectPostgreSQL’, namely
        ‘(fromString options)’
      In the first argument of ‘bracket’, namely
        ‘(Pg.connectPostgreSQL (fromString options))’
    |
109 |                             bracket (Pg.connectPostgreSQL (fromString options)) Pg.close $ \conn ->
    |                                                                       ^^^^^^^

**Comment by xiaoshihou514** [comment]
Glad to see it resolved! Can confirm builds fine with GHC 9.6.7
